const appname = "The Civilian";
const appversion = "Version 1.0.0";
const credits = "@sdslab";
const email="Email";
const emailhint="admin@she.com";
const password="Password";
const passwordhint="*********";
const forgetpass="Forget Password";
const retypepass="Confirm Password";
const loggedinsuccessfully="Logged In Successfully";
const loggedoutsuccessfully="Logged Out Successfully";
const name="Name";
const namehint="admin";
const login="Log in";
const signup="Sign Up";
const createnewaccount="or,create a new account";
const loginwith="log In With";
const privacypolicy="Privacy Policy";
const termsandcondition="Terms and Condition";
const alreadyhaveaccount="Already have an account ? ";
const homey="Home",categories="Categories",cart="Cart",account="Account";
const searchany="Search anything...", todaydeal="Today`s Deal", flashsale="Flash Sale", topsellers="Top Sellers",brand="Brands",topcategories="Top Catergories",featuredcategores="Features Categories";
const stickers="Stickers";
const mobilecover="Mobile Covers";
const laptopstickers="Laptop`s Stickers";
const laptopcover="Laptop`s Cover";
const featuredproduct="Featured Products";
const description="Description";
const price="XXXXX";
const video="Vides",review="Reviews",sellerpolicy="Seller`s Policy",returnpolicy="Return Policy",prodcutyoumaylike="Prodcuts you may also like";
const wishlist="My Wishlist",order="My Orders",message="Messages";
const cartcount=00;
const wishlistcount=00;
const yourordercount=00;
const oldpass="Old Password";
const newpass="New Password";